# このファイルは gen.py が internal/api.h と internal/funcs.h から生成する。直接編集しない。
"""beth.dll / libbeth.so の内部層(beth::internal)の Python バインディング。

- lib.<DLL の関数名>(...) で呼ぶ。DLL の中で例外が起きると BethError を送出する(docs/adr/0031)。
- コールバックの引数には Python の関数をそのまま渡せる。渡したコールバックは、同じ登録先
  (関数名と対象のオブジェクト)に次のコールバックを登録するまで保持する(GC で解放されないように)。
- コールバックの中で起きた Python の例外は SetCallbackError で DLL へ知らせる。公開関数の中
  (Show・Click 等)で起きたものは、その関数の呼び出し側で BethError(__cause__ が元の例外)になり、
  メッセージループの中で起きたものは LCL の Application.HandleException が処理する。
- コールバックは DLL を呼んだスレッド(GUI の処理は TApplication_Run を呼んだスレッド)の上で呼ばれる。
"""
import os
import platform
import threading
import ctypes
from ctypes import POINTER, c_void_p, c_char_p, c_char, c_int, c_uint, c_ssize_t, c_double

# 基本型(internal/api.h)
obj_t = c_void_p
str_t = c_char_p   # UTF-8 の bytes
int_t = c_int
uint_t = c_uint
bool_t = c_int     # Pascal の LongBool。0 以外は真(DLL が返す真は -1)
real_t = c_double
iptr_t = c_ssize_t  # ポインタと同じ幅の符号付き整数(Pascal の PtrInt。TComponent の Tag)

# DLL の呼び出し規約は Windows では __stdcall(Win64 では cdecl と同じ)
if platform.system() == "Windows":
    _FUNCTYPE = ctypes.WINFUNCTYPE
    _dll = ctypes.WinDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)), "beth.dll"))
else:
    _FUNCTYPE = ctypes.CFUNCTYPE
    _dll = ctypes.CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)), "libbeth.so"))


class BethError(Exception):
    """DLL の中で起きた例外。class_name は Pascal の例外クラス名(コールバック由来なら元の例外のクラス名)。
    C++ の beth::Exception と同じ名前でも読める(E.Message・E.ClassName())。"""

    def __init__(self, class_name, message):
        super().__init__(f"{class_name}: {message}")
        self.class_name = class_name
        self.message = message

    @property
    def Message(self):
        return self.message

    def ClassName(self):
        return self.class_name


# 直前のエラー(docs/adr/0031)。DLL は失敗した呼び出しと同じスレッドで、その呼び出しから戻る前に知らせる。
_state = threading.local()

_error_callback_t = _FUNCTYPE(None, c_char_p, c_char_p)


def _on_dll_error(class_name, message):
    _state.error = ((class_name or b"").decode("utf-8", "replace"), (message or b"").decode("utf-8", "replace"))


_on_dll_error_ref = _error_callback_t(_on_dll_error)
_dll.Error_SetCallback.argtypes = [_error_callback_t]
_dll.Error_SetCallback.restype = None
_dll.Error_SetCallback(_on_dll_error_ref)


def _errcheck(result, func, args):
    error = getattr(_state, "error", None)
    if error is None:
        return result
    _state.error = None
    cause = getattr(_state, "callback_exception", None)
    _state.callback_exception = None
    raise BethError(*error) from cause


def _guard(fn):
    """コールバックの本体を包み、Python の例外を SetCallbackError で DLL へ知らせる。"""

    def guarded(*args):
        try:
            fn(*args)
        except BaseException as e:
            _state.callback_exception = e
            if isinstance(e, BethError):
                # DLL の例外・利用者が送出した BethError は、元のクラス名とメッセージのまま伝える
                class_name, message = e.class_name, e.message
            else:
                class_name, message = type(e).__name__, str(e)
            _dll.SetCallbackError(class_name.encode("utf-8"), message.encode("utf-8", "replace"))

    return guarded


# 登録中のコールバック。キーは (関数名, 対象のオブジェクト)
_callbacks = {}


def _key_of(value):
    if isinstance(value, c_void_p):
        return value.value
    return value


def _to_callback(proto, fn):
    if fn is None:
        return proto()  # NULL(コールバックの解除)
    if isinstance(fn, proto):
        return fn
    return proto(_guard(fn))


class _Lib:
    pass


lib = _Lib()


def _bind(name, restype, argtypes, callback_index=None):
    f = getattr(_dll, name)
    f.restype = restype
    f.argtypes = argtypes
    f.errcheck = _errcheck
    if callback_index is None:
        setattr(lib, name, f)
        return
    proto = argtypes[callback_index]
    has_owner = callback_index > 0

    def call(*args):
        args = list(args)
        cb = _to_callback(proto, args[callback_index])
        args[callback_index] = cb
        _callbacks[(name, _key_of(args[0]) if has_owner else None)] = cb
        return f(*args)

    call.__name__ = name
    setattr(lib, name, call)


# コールバック型(internal/api.h)

callback_t = _FUNCTYPE(None, obj_t, c_void_p)
close_callback_t = _FUNCTYPE(None, obj_t, POINTER(int_t), c_void_p)
close_query_callback_t = _FUNCTYPE(None, obj_t, POINTER(bool_t), c_void_p)
bool_callback_t = _FUNCTYPE(None, obj_t, bool_t, c_void_p)
exception_callback_t = _FUNCTYPE(None, obj_t, str_t, str_t, c_void_p)
key_callback_t = _FUNCTYPE(None, obj_t, POINTER(int_t), int_t, c_void_p)
key_press_callback_t = _FUNCTYPE(None, obj_t, POINTER(int_t), c_void_p)
mouse_callback_t = _FUNCTYPE(None, obj_t, int_t, int_t, int_t, int_t, c_void_p)
mouse_move_callback_t = _FUNCTYPE(None, obj_t, int_t, int_t, int_t, c_void_p)
mouse_wheel_callback_t = _FUNCTYPE(None, obj_t, int_t, int_t, int_t, int_t, POINTER(bool_t), c_void_p)
item_callback_t = _FUNCTYPE(None, obj_t, obj_t, c_void_p)
item_allow_callback_t = _FUNCTYPE(None, obj_t, obj_t, POINTER(bool_t), c_void_p)
item_int_callback_t = _FUNCTYPE(None, obj_t, obj_t, int_t, c_void_p)
cell_callback_t = _FUNCTYPE(None, obj_t, int_t, int_t, c_void_p)
header_callback_t = _FUNCTYPE(None, obj_t, int_t, int_t, c_void_p)
cell_allow_callback_t = _FUNCTYPE(None, obj_t, int_t, int_t, POINTER(bool_t), c_void_p)
draw_cell_callback_t = _FUNCTYPE(None, obj_t, int_t, int_t, int_t, int_t, int_t, int_t, uint_t, c_void_p)
section_track_callback_t = _FUNCTYPE(None, obj_t, obj_t, int_t, int_t, c_void_p)
section_drag_callback_t = _FUNCTYPE(None, obj_t, obj_t, obj_t, POINTER(bool_t), c_void_p)
item_rect_callback_t = _FUNCTYPE(None, obj_t, obj_t, int_t, int_t, int_t, int_t, c_void_p)

# 関数(internal/funcs.h)
_bind('SetCallbackError', None, [str_t, str_t])
_bind('FreeNotify_SetCallback', None, [callback_t, c_void_p], 0)
_bind('TComponent_Destroy', None, [obj_t])
_bind('TComponent_DestroyComponents', None, [obj_t])
_bind('TControl_GetParent', obj_t, [obj_t])
_bind('TControl_SetParent', None, [obj_t, obj_t])
_bind('TControl_GetLeft', int_t, [obj_t])
_bind('TControl_SetLeft', None, [obj_t, int_t])
_bind('TControl_GetTop', int_t, [obj_t])
_bind('TControl_SetTop', None, [obj_t, int_t])
_bind('TControl_GetWidth', int_t, [obj_t])
_bind('TControl_SetWidth', None, [obj_t, int_t])
_bind('TControl_GetHeight', int_t, [obj_t])
_bind('TControl_SetHeight', None, [obj_t, int_t])
_bind('TControl_GetVisible', bool_t, [obj_t])
_bind('TControl_SetVisible', None, [obj_t, bool_t])
_bind('TControl_GetEnabled', bool_t, [obj_t])
_bind('TControl_SetEnabled', None, [obj_t, bool_t])
_bind('TControl_GetCaption', str_t, [obj_t])
_bind('TControl_SetCaption', None, [obj_t, str_t])
_bind('TControl_GetAlign', int_t, [obj_t])
_bind('TControl_SetAlign', None, [obj_t, int_t])
_bind('TControl_GetAutoSize', bool_t, [obj_t])
_bind('TControl_SetAutoSize', None, [obj_t, bool_t])
_bind('TControl_GetText', str_t, [obj_t])
_bind('TControl_SetText', None, [obj_t, str_t])
_bind('TControl_Show', None, [obj_t])
_bind('TControl_Hide', None, [obj_t])
_bind('TControl_SetOnClick', None, [obj_t, callback_t, c_void_p], 1)
_bind('TControl_SetOnDblClick', None, [obj_t, callback_t, c_void_p], 1)
_bind('TControl_SetOnResize', None, [obj_t, callback_t, c_void_p], 1)
_bind('TControl_SetOnMouseDown', None, [obj_t, mouse_callback_t, c_void_p], 1)
_bind('TControl_SetOnMouseUp', None, [obj_t, mouse_callback_t, c_void_p], 1)
_bind('TControl_SetOnMouseMove', None, [obj_t, mouse_move_callback_t, c_void_p], 1)
_bind('TControl_SetOnMouseEnter', None, [obj_t, callback_t, c_void_p], 1)
_bind('TControl_SetOnMouseLeave', None, [obj_t, callback_t, c_void_p], 1)
_bind('TControl_SetOnMouseWheel', None, [obj_t, mouse_wheel_callback_t, c_void_p], 1)
_bind('TWinControl_SetOnKeyDown', None, [obj_t, key_callback_t, c_void_p], 1)
_bind('TWinControl_SetOnKeyUp', None, [obj_t, key_callback_t, c_void_p], 1)
_bind('TWinControl_SetOnKeyPress', None, [obj_t, key_press_callback_t, c_void_p], 1)
_bind('TForm_Create', obj_t, [obj_t])
_bind('TCustomForm_Show', None, [obj_t])
_bind('TCustomForm_Hide', None, [obj_t])
_bind('TCustomForm_ShowModal', int_t, [obj_t])
_bind('TCustomForm_Close', None, [obj_t])
_bind('TCustomForm_Release', None, [obj_t])
_bind('TCustomForm_SetOnClose', None, [obj_t, close_callback_t, c_void_p], 1)
_bind('TCustomForm_SetOnCloseQuery', None, [obj_t, close_query_callback_t, c_void_p], 1)
_bind('TCustomForm_SetOnShow', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomForm_SetOnHide', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomForm_SetOnActivate', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomForm_SetOnDeactivate', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomForm_SetOnDestroy', None, [obj_t, callback_t, c_void_p], 1)
_bind('GetApplication', obj_t, [])
_bind('TApplication_CreateForm', obj_t, [obj_t])
_bind('TApplication_GetMainForm', obj_t, [obj_t])
_bind('TApplication_Run', None, [obj_t])
_bind('TApplication_ProcessMessages', None, [obj_t])
_bind('TApplication_Terminate', None, [obj_t])
_bind('TApplication_GetTerminated', bool_t, [obj_t])
_bind('TApplication_GetTitle', str_t, [obj_t])
_bind('TApplication_SetTitle', None, [obj_t, str_t])
_bind('TApplication_GetShowMainForm', bool_t, [obj_t])
_bind('TApplication_SetShowMainForm', None, [obj_t, bool_t])
_bind('TPanel_Create', obj_t, [obj_t])
_bind('TGroupBox_Create', obj_t, [obj_t])
_bind('TLabel_Create', obj_t, [obj_t])
_bind('TButtonControl_GetChecked', bool_t, [obj_t])
_bind('TButtonControl_SetChecked', None, [obj_t, bool_t])
_bind('TButton_Create', obj_t, [obj_t])
_bind('TCheckBox_Create', obj_t, [obj_t])
_bind('TRadioButton_Create', obj_t, [obj_t])
_bind('TCustomEdit_GetMaxLength', int_t, [obj_t])
_bind('TCustomEdit_SetMaxLength', None, [obj_t, int_t])
_bind('TCustomEdit_GetReadOnly', bool_t, [obj_t])
_bind('TCustomEdit_SetReadOnly', None, [obj_t, bool_t])
_bind('TCustomEdit_SetOnChange', None, [obj_t, callback_t, c_void_p], 1)
_bind('TEdit_Create', obj_t, [obj_t])
_bind('TCustomMemo_GetLines', obj_t, [obj_t])
_bind('TCustomMemo_GetScrollBars', int_t, [obj_t])
_bind('TCustomMemo_SetScrollBars', None, [obj_t, int_t])
_bind('TMemo_Create', obj_t, [obj_t])
_bind('TCustomComboBox_GetItemIndex', int_t, [obj_t])
_bind('TCustomComboBox_SetItemIndex', None, [obj_t, int_t])
_bind('TCustomComboBox_GetItems', obj_t, [obj_t])
_bind('TComboBox_Create', obj_t, [obj_t])
_bind('TComboBox_SetOnChange', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomListBox_GetItemIndex', int_t, [obj_t])
_bind('TCustomListBox_SetItemIndex', None, [obj_t, int_t])
_bind('TCustomListBox_GetItems', obj_t, [obj_t])
_bind('TListBox_Create', obj_t, [obj_t])
_bind('TCustomTimer_GetInterval', int_t, [obj_t])
_bind('TCustomTimer_SetInterval', None, [obj_t, int_t])
_bind('TCustomTimer_GetEnabled', bool_t, [obj_t])
_bind('TCustomTimer_SetEnabled', None, [obj_t, bool_t])
_bind('TCustomTimer_SetOnTimer', None, [obj_t, callback_t, c_void_p], 1)
_bind('TTimer_Create', obj_t, [obj_t])
_bind('TPaintBox_Create', obj_t, [obj_t])
_bind('TPaintBox_GetCanvas', obj_t, [obj_t])
_bind('TPaintBox_SetOnPaint', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCanvas_MoveTo', None, [obj_t, int_t, int_t])
_bind('TCanvas_LineTo', None, [obj_t, int_t, int_t])
_bind('TCanvas_Rectangle', None, [obj_t, int_t, int_t, int_t, int_t])
_bind('TCanvas_Ellipse', None, [obj_t, int_t, int_t, int_t, int_t])
_bind('TCanvas_TextOut', None, [obj_t, int_t, int_t, str_t])
_bind('TCanvas_GetPen', obj_t, [obj_t])
_bind('TCanvas_GetBrush', obj_t, [obj_t])
_bind('TCanvas_GetFont', obj_t, [obj_t])
_bind('TCanvas_Draw', None, [obj_t, int_t, int_t, obj_t])
_bind('TCanvas_StretchDraw', None, [obj_t, int_t, int_t, int_t, int_t, obj_t])
_bind('TCanvas_FillRect', None, [obj_t, int_t, int_t, int_t, int_t])
_bind('TCanvas_GetPixels', int_t, [obj_t, int_t, int_t])
_bind('TCanvas_SetPixels', None, [obj_t, int_t, int_t, int_t])
_bind('TPen_GetColor', int_t, [obj_t])
_bind('TPen_SetColor', None, [obj_t, int_t])
_bind('TPen_GetWidth', int_t, [obj_t])
_bind('TPen_SetWidth', None, [obj_t, int_t])
_bind('TBrush_GetColor', int_t, [obj_t])
_bind('TBrush_SetColor', None, [obj_t, int_t])
_bind('TFont_GetName', str_t, [obj_t])
_bind('TFont_SetName', None, [obj_t, str_t])
_bind('TFont_GetSize', int_t, [obj_t])
_bind('TFont_SetSize', None, [obj_t, int_t])
_bind('TFont_GetColor', int_t, [obj_t])
_bind('TFont_SetColor', None, [obj_t, int_t])
_bind('TScrollBox_Create', obj_t, [obj_t])
_bind('TToggleBox_Create', obj_t, [obj_t])
_bind('TBevel_Create', obj_t, [obj_t])
_bind('TBevel_GetShape', int_t, [obj_t])
_bind('TBevel_SetShape', None, [obj_t, int_t])
_bind('TBevel_GetStyle', int_t, [obj_t])
_bind('TBevel_SetStyle', None, [obj_t, int_t])
_bind('TShape_Create', obj_t, [obj_t])
_bind('TCustomShape_GetShape', int_t, [obj_t])
_bind('TCustomShape_SetShape', None, [obj_t, int_t])
_bind('TCustomShape_GetPen', obj_t, [obj_t])
_bind('TCustomShape_GetBrush', obj_t, [obj_t])
_bind('TStaticText_Create', obj_t, [obj_t])
_bind('TCustomStaticText_GetBorderStyle', int_t, [obj_t])
_bind('TCustomStaticText_SetBorderStyle', None, [obj_t, int_t])
_bind('TStatusBar_Create', obj_t, [obj_t])
_bind('TStatusBar_GetSimpleText', str_t, [obj_t])
_bind('TStatusBar_SetSimpleText', None, [obj_t, str_t])
_bind('TStatusBar_GetSimplePanel', bool_t, [obj_t])
_bind('TStatusBar_SetSimplePanel', None, [obj_t, bool_t])
_bind('TScrollBar_Create', obj_t, [obj_t])
_bind('TCustomScrollBar_GetKind', int_t, [obj_t])
_bind('TCustomScrollBar_SetKind', None, [obj_t, int_t])
_bind('TCustomScrollBar_GetMin', int_t, [obj_t])
_bind('TCustomScrollBar_SetMin', None, [obj_t, int_t])
_bind('TCustomScrollBar_GetMax', int_t, [obj_t])
_bind('TCustomScrollBar_SetMax', None, [obj_t, int_t])
_bind('TCustomScrollBar_GetPosition', int_t, [obj_t])
_bind('TCustomScrollBar_SetPosition', None, [obj_t, int_t])
_bind('TCustomScrollBar_GetPageSize', int_t, [obj_t])
_bind('TCustomScrollBar_SetPageSize', None, [obj_t, int_t])
_bind('TCustomScrollBar_SetOnChange', None, [obj_t, callback_t, c_void_p], 1)
_bind('TTrackBar_Create', obj_t, [obj_t])
_bind('TCustomTrackBar_GetMin', int_t, [obj_t])
_bind('TCustomTrackBar_SetMin', None, [obj_t, int_t])
_bind('TCustomTrackBar_GetMax', int_t, [obj_t])
_bind('TCustomTrackBar_SetMax', None, [obj_t, int_t])
_bind('TCustomTrackBar_GetPosition', int_t, [obj_t])
_bind('TCustomTrackBar_SetPosition', None, [obj_t, int_t])
_bind('TCustomTrackBar_SetOnChange', None, [obj_t, callback_t, c_void_p], 1)
_bind('TProgressBar_Create', obj_t, [obj_t])
_bind('TCustomProgressBar_GetMin', int_t, [obj_t])
_bind('TCustomProgressBar_SetMin', None, [obj_t, int_t])
_bind('TCustomProgressBar_GetMax', int_t, [obj_t])
_bind('TCustomProgressBar_SetMax', None, [obj_t, int_t])
_bind('TCustomProgressBar_GetPosition', int_t, [obj_t])
_bind('TCustomProgressBar_SetPosition', None, [obj_t, int_t])
_bind('TUpDown_Create', obj_t, [obj_t])
_bind('TUpDown_GetMin', int_t, [obj_t])
_bind('TUpDown_SetMin', None, [obj_t, int_t])
_bind('TUpDown_GetMax', int_t, [obj_t])
_bind('TUpDown_SetMax', None, [obj_t, int_t])
_bind('TUpDown_GetPosition', int_t, [obj_t])
_bind('TUpDown_SetPosition', None, [obj_t, int_t])
_bind('TUpDown_GetIncrement', int_t, [obj_t])
_bind('TUpDown_SetIncrement', None, [obj_t, int_t])
_bind('TUpDown_GetAssociate', obj_t, [obj_t])
_bind('TUpDown_SetAssociate', None, [obj_t, obj_t])
_bind('TRadioGroup_Create', obj_t, [obj_t])
_bind('TCustomRadioGroup_GetItems', obj_t, [obj_t])
_bind('TCustomRadioGroup_GetItemIndex', int_t, [obj_t])
_bind('TCustomRadioGroup_SetItemIndex', None, [obj_t, int_t])
_bind('TCustomRadioGroup_SetOnClick', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCheckGroup_Create', obj_t, [obj_t])
_bind('TCustomCheckGroup_GetItems', obj_t, [obj_t])
_bind('TCustomCheckGroup_GetChecked', bool_t, [obj_t, int_t])
_bind('TCustomCheckGroup_SetChecked', None, [obj_t, int_t, bool_t])
_bind('TCheckListBox_Create', obj_t, [obj_t])
_bind('TCustomCheckListBox_GetChecked', bool_t, [obj_t, int_t])
_bind('TCustomCheckListBox_SetChecked', None, [obj_t, int_t, bool_t])
_bind('TCustomCheckListBox_SetOnClickCheck', None, [obj_t, callback_t, c_void_p], 1)
_bind('TSpeedButton_Create', obj_t, [obj_t])
_bind('TCustomSpeedButton_GetDown', bool_t, [obj_t])
_bind('TCustomSpeedButton_SetDown', None, [obj_t, bool_t])
_bind('TCustomSpeedButton_GetGroupIndex', int_t, [obj_t])
_bind('TCustomSpeedButton_SetGroupIndex', None, [obj_t, int_t])
_bind('TCustomSpeedButton_GetFlat', bool_t, [obj_t])
_bind('TCustomSpeedButton_SetFlat', None, [obj_t, bool_t])
_bind('TCustomSpeedButton_GetAllowAllUp', bool_t, [obj_t])
_bind('TCustomSpeedButton_SetAllowAllUp', None, [obj_t, bool_t])
_bind('TBitBtn_Create', obj_t, [obj_t])
_bind('TCustomBitBtn_GetKind', int_t, [obj_t])
_bind('TCustomBitBtn_SetKind', None, [obj_t, int_t])
_bind('TFloatSpinEdit_Create', obj_t, [obj_t])
_bind('TCustomFloatSpinEdit_GetValue', real_t, [obj_t])
_bind('TCustomFloatSpinEdit_SetValue', None, [obj_t, real_t])
_bind('TCustomFloatSpinEdit_GetMinValue', real_t, [obj_t])
_bind('TCustomFloatSpinEdit_SetMinValue', None, [obj_t, real_t])
_bind('TCustomFloatSpinEdit_GetMaxValue', real_t, [obj_t])
_bind('TCustomFloatSpinEdit_SetMaxValue', None, [obj_t, real_t])
_bind('TCustomFloatSpinEdit_GetIncrement', real_t, [obj_t])
_bind('TCustomFloatSpinEdit_SetIncrement', None, [obj_t, real_t])
_bind('TCustomFloatSpinEdit_GetDecimalPlaces', int_t, [obj_t])
_bind('TCustomFloatSpinEdit_SetDecimalPlaces', None, [obj_t, int_t])
_bind('TSpinEdit_Create', obj_t, [obj_t])
_bind('TCustomSpinEdit_GetValue', int_t, [obj_t])
_bind('TCustomSpinEdit_SetValue', None, [obj_t, int_t])
_bind('TCustomSpinEdit_GetMinValue', int_t, [obj_t])
_bind('TCustomSpinEdit_SetMinValue', None, [obj_t, int_t])
_bind('TCustomSpinEdit_GetMaxValue', int_t, [obj_t])
_bind('TCustomSpinEdit_SetMaxValue', None, [obj_t, int_t])
_bind('TCustomSpinEdit_GetIncrement', int_t, [obj_t])
_bind('TCustomSpinEdit_SetIncrement', None, [obj_t, int_t])
_bind('TMaskEdit_Create', obj_t, [obj_t])
_bind('TMaskEdit_GetEditMask', str_t, [obj_t])
_bind('TMaskEdit_SetEditMask', None, [obj_t, str_t])
_bind('TLabeledEdit_Create', obj_t, [obj_t])
_bind('TCustomLabeledEdit_GetEditLabel', obj_t, [obj_t])
_bind('TCustomLabeledEdit_GetLabelPosition', int_t, [obj_t])
_bind('TCustomLabeledEdit_SetLabelPosition', None, [obj_t, int_t])
_bind('TCustomLabeledEdit_GetLabelSpacing', int_t, [obj_t])
_bind('TCustomLabeledEdit_SetLabelSpacing', None, [obj_t, int_t])
_bind('TTabControl_Create', obj_t, [obj_t])
_bind('TTabControl_GetTabs', obj_t, [obj_t])
_bind('TTabControl_GetTabIndex', int_t, [obj_t])
_bind('TTabControl_SetTabIndex', None, [obj_t, int_t])
_bind('TTabControl_SetOnChange', None, [obj_t, callback_t, c_void_p], 1)
_bind('TSplitter_Create', obj_t, [obj_t])
_bind('TCustomSplitter_GetAutoSnap', bool_t, [obj_t])
_bind('TCustomSplitter_SetAutoSnap', None, [obj_t, bool_t])
_bind('TCustomSplitter_GetBeveled', bool_t, [obj_t])
_bind('TCustomSplitter_SetBeveled', None, [obj_t, bool_t])
_bind('TCustomSplitter_GetMinSize', int_t, [obj_t])
_bind('TCustomSplitter_SetMinSize', None, [obj_t, int_t])
_bind('TCustomSplitter_GetResizeAnchor', int_t, [obj_t])
_bind('TCustomSplitter_SetResizeAnchor', None, [obj_t, int_t])
_bind('TCustomSplitter_GetResizeStyle', int_t, [obj_t])
_bind('TCustomSplitter_SetResizeStyle', None, [obj_t, int_t])
_bind('TCustomSplitter_GetSplitterPosition', int_t, [obj_t])
_bind('TCustomSplitter_SetSplitterPosition', None, [obj_t, int_t])
_bind('TCustomSplitter_SetOnMoved', None, [obj_t, callback_t, c_void_p], 1)
_bind('ShortCut_Make', int_t, [int_t, int_t])
_bind('ShortCut_FromText', int_t, [str_t])
_bind('ShortCut_ToText', str_t, [int_t])
_bind('TMenuItem_Create', obj_t, [obj_t])
_bind('TMenuItem_GetCaption', str_t, [obj_t])
_bind('TMenuItem_SetCaption', None, [obj_t, str_t])
_bind('TMenuItem_GetChecked', bool_t, [obj_t])
_bind('TMenuItem_SetChecked', None, [obj_t, bool_t])
_bind('TMenuItem_GetEnabled', bool_t, [obj_t])
_bind('TMenuItem_SetEnabled', None, [obj_t, bool_t])
_bind('TMenuItem_GetVisible', bool_t, [obj_t])
_bind('TMenuItem_SetVisible', None, [obj_t, bool_t])
_bind('TMenuItem_GetAutoCheck', bool_t, [obj_t])
_bind('TMenuItem_SetAutoCheck', None, [obj_t, bool_t])
_bind('TMenuItem_GetRadioItem', bool_t, [obj_t])
_bind('TMenuItem_SetRadioItem', None, [obj_t, bool_t])
_bind('TMenuItem_GetGroupIndex', int_t, [obj_t])
_bind('TMenuItem_SetGroupIndex', None, [obj_t, int_t])
_bind('TMenuItem_GetDefault', bool_t, [obj_t])
_bind('TMenuItem_SetDefault', None, [obj_t, bool_t])
_bind('TMenuItem_GetShortCut', int_t, [obj_t])
_bind('TMenuItem_SetShortCut', None, [obj_t, int_t])
_bind('TMenuItem_GetHint', str_t, [obj_t])
_bind('TMenuItem_SetHint', None, [obj_t, str_t])
_bind('TMenuItem_SetOnClick', None, [obj_t, callback_t, c_void_p], 1)
_bind('TMenuItem_GetCount', int_t, [obj_t])
_bind('TMenuItem_GetItem', obj_t, [obj_t, int_t])
_bind('TMenuItem_GetParent', obj_t, [obj_t])
_bind('TMenuItem_Add', None, [obj_t, obj_t])
_bind('TMenuItem_Insert', None, [obj_t, int_t, obj_t])
_bind('TMenuItem_Delete', None, [obj_t, int_t])
_bind('TMenuItem_Remove', None, [obj_t, obj_t])
_bind('TMenuItem_Clear', None, [obj_t])
_bind('TMenuItem_IndexOf', int_t, [obj_t, obj_t])
_bind('TMenuItem_AddSeparator', None, [obj_t])
_bind('TMenuItem_IsLine', bool_t, [obj_t])
_bind('TMenuItem_Click', None, [obj_t])
_bind('TMenu_GetItems', obj_t, [obj_t])
_bind('TMainMenu_Create', obj_t, [obj_t])
_bind('TPopupMenu_Create', obj_t, [obj_t])
_bind('TPopupMenu_Popup', None, [obj_t, int_t, int_t])
_bind('TPopupMenu_GetAutoPopup', bool_t, [obj_t])
_bind('TPopupMenu_SetAutoPopup', None, [obj_t, bool_t])
_bind('TPopupMenu_GetPopupComponent', obj_t, [obj_t])
_bind('TPopupMenu_SetPopupComponent', None, [obj_t, obj_t])
_bind('TPopupMenu_SetOnPopup', None, [obj_t, callback_t, c_void_p], 1)
_bind('TPopupMenu_SetOnClose', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomForm_GetMenu', obj_t, [obj_t])
_bind('TCustomForm_SetMenu', None, [obj_t, obj_t])
_bind('TControl_GetPopupMenu', obj_t, [obj_t])
_bind('TControl_SetPopupMenu', None, [obj_t, obj_t])
_bind('TPageControl_Create', obj_t, [obj_t])
_bind('TPageControl_GetActivePage', obj_t, [obj_t])
_bind('TPageControl_SetActivePage', None, [obj_t, obj_t])
_bind('TPageControl_GetActivePageIndex', int_t, [obj_t])
_bind('TPageControl_SetActivePageIndex', None, [obj_t, int_t])
_bind('TPageControl_GetPage', obj_t, [obj_t, int_t])
_bind('TCustomTabControl_GetPageCount', int_t, [obj_t])
_bind('TPageControl_AddTabSheet', obj_t, [obj_t])
_bind('TPageControl_Clear', None, [obj_t])
_bind('TPageControl_SelectNextPage', None, [obj_t, bool_t])
_bind('TPageControl_GetTabIndex', int_t, [obj_t])
_bind('TPageControl_SetTabIndex', None, [obj_t, int_t])
_bind('TPageControl_SetOnChange', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomTabControl_SetOnChanging', None, [obj_t, close_query_callback_t, c_void_p], 1)
_bind('TCustomTabControl_GetMultiLine', bool_t, [obj_t])
_bind('TCustomTabControl_SetMultiLine', None, [obj_t, bool_t])
_bind('TCustomTabControl_GetShowTabs', bool_t, [obj_t])
_bind('TCustomTabControl_SetShowTabs', None, [obj_t, bool_t])
_bind('TCustomTabControl_GetTabPosition', int_t, [obj_t])
_bind('TCustomTabControl_SetTabPosition', None, [obj_t, int_t])
_bind('TTabSheet_Create', obj_t, [obj_t])
_bind('TTabSheet_GetPageControl', obj_t, [obj_t])
_bind('TTabSheet_SetPageControl', None, [obj_t, obj_t])
_bind('TTabSheet_GetTabIndex', int_t, [obj_t])
_bind('TCustomPage_GetPageIndex', int_t, [obj_t])
_bind('TCustomPage_SetPageIndex', None, [obj_t, int_t])
_bind('TCustomPage_GetTabVisible', bool_t, [obj_t])
_bind('TCustomPage_SetTabVisible', None, [obj_t, bool_t])
_bind('TCustomPage_SetOnShow', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomPage_SetOnHide', None, [obj_t, callback_t, c_void_p], 1)
_bind('ItemFree_SetCallback', None, [callback_t, c_void_p], 0)
_bind('TTreeView_Create', obj_t, [obj_t])
_bind('TCustomTreeView_GetItems', obj_t, [obj_t])
_bind('TCustomTreeView_GetSelected', obj_t, [obj_t])
_bind('TCustomTreeView_SetSelected', None, [obj_t, obj_t])
_bind('TCustomTreeView_FullExpand', None, [obj_t])
_bind('TCustomTreeView_FullCollapse', None, [obj_t])
_bind('TCustomTreeView_AlphaSort', bool_t, [obj_t])
_bind('TCustomTreeView_GetNodeAt', obj_t, [obj_t, int_t, int_t])
_bind('TTreeView_GetReadOnly', bool_t, [obj_t])
_bind('TTreeView_SetReadOnly', None, [obj_t, bool_t])
_bind('TTreeView_GetShowLines', bool_t, [obj_t])
_bind('TTreeView_SetShowLines', None, [obj_t, bool_t])
_bind('TTreeView_GetShowRoot', bool_t, [obj_t])
_bind('TTreeView_SetShowRoot', None, [obj_t, bool_t])
_bind('TTreeView_GetShowButtons', bool_t, [obj_t])
_bind('TTreeView_SetShowButtons', None, [obj_t, bool_t])
_bind('TTreeView_GetAutoExpand', bool_t, [obj_t])
_bind('TTreeView_SetAutoExpand', None, [obj_t, bool_t])
_bind('TTreeView_GetHideSelection', bool_t, [obj_t])
_bind('TTreeView_SetHideSelection', None, [obj_t, bool_t])
_bind('TTreeView_GetRowSelect', bool_t, [obj_t])
_bind('TTreeView_SetRowSelect', None, [obj_t, bool_t])
_bind('TTreeView_SetOnChange', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TTreeView_SetOnExpanded', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TTreeView_SetOnCollapsed', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TTreeView_SetOnDeletion', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TTreeView_SetOnChanging', None, [obj_t, item_allow_callback_t, c_void_p], 1)
_bind('TTreeView_SetOnExpanding', None, [obj_t, item_allow_callback_t, c_void_p], 1)
_bind('TTreeView_SetOnCollapsing', None, [obj_t, item_allow_callback_t, c_void_p], 1)
_bind('TTreeNodes_Add', obj_t, [obj_t, obj_t, str_t])
_bind('TTreeNodes_AddFirst', obj_t, [obj_t, obj_t, str_t])
_bind('TTreeNodes_AddChild', obj_t, [obj_t, obj_t, str_t])
_bind('TTreeNodes_AddChildFirst', obj_t, [obj_t, obj_t, str_t])
_bind('TTreeNodes_Insert', obj_t, [obj_t, obj_t, str_t])
_bind('TTreeNodes_Clear', None, [obj_t])
_bind('TTreeNodes_Delete', None, [obj_t, obj_t])
_bind('TTreeNodes_GetCount', int_t, [obj_t])
_bind('TTreeNodes_GetItem', obj_t, [obj_t, int_t])
_bind('TTreeNodes_GetFirstNode', obj_t, [obj_t])
_bind('TTreeNodes_FindNodeWithText', obj_t, [obj_t, str_t])
_bind('TTreeNodes_BeginUpdate', None, [obj_t])
_bind('TTreeNodes_EndUpdate', None, [obj_t])
_bind('TTreeNode_GetText', str_t, [obj_t])
_bind('TTreeNode_SetText', None, [obj_t, str_t])
_bind('TTreeNode_GetExpanded', bool_t, [obj_t])
_bind('TTreeNode_SetExpanded', None, [obj_t, bool_t])
_bind('TTreeNode_GetSelected', bool_t, [obj_t])
_bind('TTreeNode_SetSelected', None, [obj_t, bool_t])
_bind('TTreeNode_GetHasChildren', bool_t, [obj_t])
_bind('TTreeNode_SetHasChildren', None, [obj_t, bool_t])
_bind('TTreeNode_GetData', c_void_p, [obj_t])
_bind('TTreeNode_SetData', None, [obj_t, c_void_p])
_bind('TTreeNode_GetCount', int_t, [obj_t])
_bind('TTreeNode_GetItem', obj_t, [obj_t, int_t])
_bind('TTreeNode_GetIndex', int_t, [obj_t])
_bind('TTreeNode_GetLevel', int_t, [obj_t])
_bind('TTreeNode_GetAbsoluteIndex', int_t, [obj_t])
_bind('TTreeNode_GetParent', obj_t, [obj_t])
_bind('TTreeNode_GetTreeView', obj_t, [obj_t])
_bind('TTreeNode_GetFirstChild', obj_t, [obj_t])
_bind('TTreeNode_GetLastChild', obj_t, [obj_t])
_bind('TTreeNode_GetNextSibling', obj_t, [obj_t])
_bind('TTreeNode_GetPrevSibling', obj_t, [obj_t])
_bind('TTreeNode_GetNext', obj_t, [obj_t])
_bind('TTreeNode_GetPrev', obj_t, [obj_t])
_bind('TTreeNode_IndexOf', int_t, [obj_t, obj_t])
_bind('TTreeNode_Expand', None, [obj_t, bool_t])
_bind('TTreeNode_Collapse', None, [obj_t, bool_t])
_bind('TTreeNode_Delete', None, [obj_t])
_bind('TTreeNode_DeleteChildren', None, [obj_t])
_bind('TTreeNode_MakeVisible', None, [obj_t])
_bind('TTreeNode_MoveTo', None, [obj_t, obj_t, int_t])
_bind('TListView_Create', obj_t, [obj_t])
_bind('TCustomListView_GetItems', obj_t, [obj_t])
_bind('TCustomListView_GetSelected', obj_t, [obj_t])
_bind('TCustomListView_SetSelected', None, [obj_t, obj_t])
_bind('TCustomListView_GetItemIndex', int_t, [obj_t])
_bind('TCustomListView_SetItemIndex', None, [obj_t, int_t])
_bind('TCustomListView_GetSelCount', int_t, [obj_t])
_bind('TCustomListView_GetCheckboxes', bool_t, [obj_t])
_bind('TCustomListView_SetCheckboxes', None, [obj_t, bool_t])
_bind('TCustomListView_GetGridLines', bool_t, [obj_t])
_bind('TCustomListView_SetGridLines', None, [obj_t, bool_t])
_bind('TCustomListView_GetMultiSelect', bool_t, [obj_t])
_bind('TCustomListView_SetMultiSelect', None, [obj_t, bool_t])
_bind('TCustomListView_GetReadOnly', bool_t, [obj_t])
_bind('TCustomListView_SetReadOnly', None, [obj_t, bool_t])
_bind('TCustomListView_GetRowSelect', bool_t, [obj_t])
_bind('TCustomListView_SetRowSelect', None, [obj_t, bool_t])
_bind('TCustomListView_Clear', None, [obj_t])
_bind('TCustomListView_BeginUpdate', None, [obj_t])
_bind('TCustomListView_EndUpdate', None, [obj_t])
_bind('TCustomListView_GetItemAt', obj_t, [obj_t, int_t, int_t])
_bind('TCustomListView_ClearSelection', None, [obj_t])
_bind('TCustomListView_SelectAll', None, [obj_t])
_bind('TListView_GetColumns', obj_t, [obj_t])
_bind('TListView_GetViewStyle', int_t, [obj_t])
_bind('TListView_SetViewStyle', None, [obj_t, int_t])
_bind('TListView_GetHideSelection', bool_t, [obj_t])
_bind('TListView_SetHideSelection', None, [obj_t, bool_t])
_bind('TListView_GetSortType', int_t, [obj_t])
_bind('TListView_SetSortType', None, [obj_t, int_t])
_bind('TListView_GetSortColumn', int_t, [obj_t])
_bind('TListView_SetSortColumn', None, [obj_t, int_t])
_bind('TListView_GetSortDirection', int_t, [obj_t])
_bind('TListView_SetSortDirection', None, [obj_t, int_t])
_bind('TListView_SetOnSelectItem', None, [obj_t, item_int_callback_t, c_void_p], 1)
_bind('TListView_SetOnChange', None, [obj_t, item_int_callback_t, c_void_p], 1)
_bind('TListView_SetOnDeletion', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TListView_SetOnItemChecked', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TListView_SetOnColumnClick', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TListItems_Add', obj_t, [obj_t])
_bind('TListItems_Insert', obj_t, [obj_t, int_t])
_bind('TListItems_Delete', None, [obj_t, int_t])
_bind('TListItems_Clear', None, [obj_t])
_bind('TListItems_GetCount', int_t, [obj_t])
_bind('TListItems_GetItem', obj_t, [obj_t, int_t])
_bind('TListItems_IndexOf', int_t, [obj_t, obj_t])
_bind('TListItems_FindCaption', obj_t, [obj_t, int_t, str_t, bool_t, bool_t, bool_t])
_bind('TListItems_Exchange', None, [obj_t, int_t, int_t])
_bind('TListItems_Move', None, [obj_t, int_t, int_t])
_bind('TListItems_BeginUpdate', None, [obj_t])
_bind('TListItems_EndUpdate', None, [obj_t])
_bind('TListItem_GetCaption', str_t, [obj_t])
_bind('TListItem_SetCaption', None, [obj_t, str_t])
_bind('TListItem_GetChecked', bool_t, [obj_t])
_bind('TListItem_SetChecked', None, [obj_t, bool_t])
_bind('TListItem_GetSelected', bool_t, [obj_t])
_bind('TListItem_SetSelected', None, [obj_t, bool_t])
_bind('TListItem_GetFocused', bool_t, [obj_t])
_bind('TListItem_SetFocused', None, [obj_t, bool_t])
_bind('TListItem_GetData', c_void_p, [obj_t])
_bind('TListItem_SetData', None, [obj_t, c_void_p])
_bind('TListItem_GetIndex', int_t, [obj_t])
_bind('TListItem_GetListView', obj_t, [obj_t])
_bind('TListItem_GetSubItems', obj_t, [obj_t])
_bind('TListItem_Delete', None, [obj_t])
_bind('TListItem_MakeVisible', None, [obj_t, bool_t])
_bind('TListColumns_Add', obj_t, [obj_t])
_bind('TListColumns_GetCount', int_t, [obj_t])
_bind('TListColumns_GetItem', obj_t, [obj_t, int_t])
_bind('TListColumns_Delete', None, [obj_t, int_t])
_bind('TListColumns_Clear', None, [obj_t])
_bind('TListColumn_GetCaption', str_t, [obj_t])
_bind('TListColumn_SetCaption', None, [obj_t, str_t])
_bind('TListColumn_GetWidth', int_t, [obj_t])
_bind('TListColumn_SetWidth', None, [obj_t, int_t])
_bind('TListColumn_GetAlignment', int_t, [obj_t])
_bind('TListColumn_SetAlignment', None, [obj_t, int_t])
_bind('TListColumn_GetAutoSize', bool_t, [obj_t])
_bind('TListColumn_SetAutoSize', None, [obj_t, bool_t])
_bind('TListColumn_GetVisible', bool_t, [obj_t])
_bind('TListColumn_SetVisible', None, [obj_t, bool_t])
_bind('TListColumn_GetIndex', int_t, [obj_t])
_bind('TListColumn_SetIndex', None, [obj_t, int_t])
_bind('TDrawGrid_Create', obj_t, [obj_t])
_bind('TStringGrid_Create', obj_t, [obj_t])
_bind('TCustomGrid_BeginUpdate', None, [obj_t])
_bind('TCustomGrid_EndUpdate', None, [obj_t])
_bind('TCustomGrid_Clear', None, [obj_t])
_bind('TCustomGrid_CellRect', None, [obj_t, int_t, int_t, POINTER(int_t), POINTER(int_t), POINTER(int_t), POINTER(int_t)])
_bind('TCustomGrid_MouseToCell', None, [obj_t, int_t, int_t, POINTER(int_t), POINTER(int_t)])
_bind('TCustomDrawGrid_GetColCount', int_t, [obj_t])
_bind('TCustomDrawGrid_SetColCount', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetRowCount', int_t, [obj_t])
_bind('TCustomDrawGrid_SetRowCount', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetFixedCols', int_t, [obj_t])
_bind('TCustomDrawGrid_SetFixedCols', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetFixedRows', int_t, [obj_t])
_bind('TCustomDrawGrid_SetFixedRows', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetCol', int_t, [obj_t])
_bind('TCustomDrawGrid_SetCol', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetRow', int_t, [obj_t])
_bind('TCustomDrawGrid_SetRow', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetDefaultColWidth', int_t, [obj_t])
_bind('TCustomDrawGrid_SetDefaultColWidth', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetDefaultRowHeight', int_t, [obj_t])
_bind('TCustomDrawGrid_SetDefaultRowHeight', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetColWidths', int_t, [obj_t, int_t])
_bind('TCustomDrawGrid_SetColWidths', None, [obj_t, int_t, int_t])
_bind('TCustomDrawGrid_GetRowHeights', int_t, [obj_t, int_t])
_bind('TCustomDrawGrid_SetRowHeights', None, [obj_t, int_t, int_t])
_bind('TCustomDrawGrid_GetOptions', uint_t, [obj_t])
_bind('TCustomDrawGrid_SetOptions', None, [obj_t, uint_t])
_bind('TCustomDrawGrid_GetSelection', None, [obj_t, POINTER(int_t), POINTER(int_t), POINTER(int_t), POINTER(int_t)])
_bind('TCustomDrawGrid_SetSelection', None, [obj_t, int_t, int_t, int_t, int_t])
_bind('TCustomDrawGrid_GetLeftCol', int_t, [obj_t])
_bind('TCustomDrawGrid_SetLeftCol', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetTopRow', int_t, [obj_t])
_bind('TCustomDrawGrid_SetTopRow', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetDefaultDrawing', bool_t, [obj_t])
_bind('TCustomDrawGrid_SetDefaultDrawing', None, [obj_t, bool_t])
_bind('TCustomDrawGrid_GetFixedColor', int_t, [obj_t])
_bind('TCustomDrawGrid_SetFixedColor', None, [obj_t, int_t])
_bind('TCustomDrawGrid_GetEditorMode', bool_t, [obj_t])
_bind('TCustomDrawGrid_SetEditorMode', None, [obj_t, bool_t])
_bind('TCustomDrawGrid_InsertColRow', None, [obj_t, bool_t, int_t])
_bind('TCustomDrawGrid_DeleteColRow', None, [obj_t, bool_t, int_t])
_bind('TCustomDrawGrid_MoveColRow', None, [obj_t, bool_t, int_t, int_t])
_bind('TCustomDrawGrid_SortColRow', None, [obj_t, bool_t, int_t])
_bind('TCustomDrawGrid_SetOnDrawCell', None, [obj_t, draw_cell_callback_t, c_void_p], 1)
_bind('TCustomDrawGrid_SetOnSelectCell', None, [obj_t, cell_allow_callback_t, c_void_p], 1)
_bind('TCustomDrawGrid_SetOnSelection', None, [obj_t, cell_callback_t, c_void_p], 1)
_bind('TCustomDrawGrid_SetOnHeaderClick', None, [obj_t, header_callback_t, c_void_p], 1)
_bind('TCustomStringGrid_GetCells', str_t, [obj_t, int_t, int_t])
_bind('TCustomStringGrid_SetCells', None, [obj_t, int_t, int_t, str_t])
_bind('TCustomStringGrid_Clean', None, [obj_t])
_bind('TCustomStringGrid_AutoSizeColumns', None, [obj_t])
_bind('TCustomStringGrid_AutoSizeColumn', None, [obj_t, int_t])
_bind('THeaderControl_Create', obj_t, [obj_t])
_bind('TCustomHeaderControl_GetSections', obj_t, [obj_t])
_bind('TCustomHeaderControl_GetDragReorder', bool_t, [obj_t])
_bind('TCustomHeaderControl_SetDragReorder', None, [obj_t, bool_t])
_bind('TCustomHeaderControl_GetSectionAt', int_t, [obj_t, int_t, int_t])
_bind('TCustomHeaderControl_GetSectionFromOriginalIndex', obj_t, [obj_t, int_t])
_bind('TCustomHeaderControl_SetOnSectionClick', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TCustomHeaderControl_SetOnSectionResize', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TCustomHeaderControl_SetOnSectionSeparatorDblClick', None, [obj_t, item_callback_t, c_void_p], 1)
_bind('TCustomHeaderControl_SetOnSectionTrack', None, [obj_t, section_track_callback_t, c_void_p], 1)
_bind('TCustomHeaderControl_SetOnSectionDrag', None, [obj_t, section_drag_callback_t, c_void_p], 1)
_bind('TCustomHeaderControl_SetOnSectionEndDrag', None, [obj_t, callback_t, c_void_p], 1)
_bind('THeaderSections_Add', obj_t, [obj_t])
_bind('THeaderSections_Insert', obj_t, [obj_t, int_t])
_bind('THeaderSections_Delete', None, [obj_t, int_t])
_bind('THeaderSections_Clear', None, [obj_t])
_bind('THeaderSections_GetCount', int_t, [obj_t])
_bind('THeaderSections_GetItem', obj_t, [obj_t, int_t])
_bind('THeaderSections_BeginUpdate', None, [obj_t])
_bind('THeaderSections_EndUpdate', None, [obj_t])
_bind('THeaderSection_GetText', str_t, [obj_t])
_bind('THeaderSection_SetText', None, [obj_t, str_t])
_bind('THeaderSection_GetWidth', int_t, [obj_t])
_bind('THeaderSection_SetWidth', None, [obj_t, int_t])
_bind('THeaderSection_GetMinWidth', int_t, [obj_t])
_bind('THeaderSection_SetMinWidth', None, [obj_t, int_t])
_bind('THeaderSection_GetMaxWidth', int_t, [obj_t])
_bind('THeaderSection_SetMaxWidth', None, [obj_t, int_t])
_bind('THeaderSection_GetAlignment', int_t, [obj_t])
_bind('THeaderSection_SetAlignment', None, [obj_t, int_t])
_bind('THeaderSection_GetVisible', bool_t, [obj_t])
_bind('THeaderSection_SetVisible', None, [obj_t, bool_t])
_bind('THeaderSection_GetIndex', int_t, [obj_t])
_bind('THeaderSection_SetIndex', None, [obj_t, int_t])
_bind('THeaderSection_GetLeft', int_t, [obj_t])
_bind('THeaderSection_GetRight', int_t, [obj_t])
_bind('THeaderSection_GetOriginalIndex', int_t, [obj_t])
_bind('TToolWindow_GetEdgeBorders', uint_t, [obj_t])
_bind('TToolWindow_SetEdgeBorders', None, [obj_t, uint_t])
_bind('TToolWindow_GetEdgeInner', int_t, [obj_t])
_bind('TToolWindow_SetEdgeInner', None, [obj_t, int_t])
_bind('TToolWindow_GetEdgeOuter', int_t, [obj_t])
_bind('TToolWindow_SetEdgeOuter', None, [obj_t, int_t])
_bind('TToolWindow_BeginUpdate', None, [obj_t])
_bind('TToolWindow_EndUpdate', None, [obj_t])
_bind('TToolBar_Create', obj_t, [obj_t])
_bind('TToolBar_GetButtonCount', int_t, [obj_t])
_bind('TToolBar_GetButton', obj_t, [obj_t, int_t])
_bind('TToolBar_GetRowCount', int_t, [obj_t])
_bind('TToolBar_GetButtonHeight', int_t, [obj_t])
_bind('TToolBar_SetButtonHeight', None, [obj_t, int_t])
_bind('TToolBar_GetButtonWidth', int_t, [obj_t])
_bind('TToolBar_SetButtonWidth', None, [obj_t, int_t])
_bind('TToolBar_GetDropDownWidth', int_t, [obj_t])
_bind('TToolBar_SetDropDownWidth', None, [obj_t, int_t])
_bind('TToolBar_GetIndent', int_t, [obj_t])
_bind('TToolBar_SetIndent', None, [obj_t, int_t])
_bind('TToolBar_GetFlat', bool_t, [obj_t])
_bind('TToolBar_SetFlat', None, [obj_t, bool_t])
_bind('TToolBar_GetList', bool_t, [obj_t])
_bind('TToolBar_SetList', None, [obj_t, bool_t])
_bind('TToolBar_GetShowCaptions', bool_t, [obj_t])
_bind('TToolBar_SetShowCaptions', None, [obj_t, bool_t])
_bind('TToolBar_GetTransparent', bool_t, [obj_t])
_bind('TToolBar_SetTransparent', None, [obj_t, bool_t])
_bind('TToolBar_GetWrapable', bool_t, [obj_t])
_bind('TToolBar_SetWrapable', None, [obj_t, bool_t])
_bind('TToolBar_SetButtonSize', None, [obj_t, int_t, int_t])
_bind('TToolButton_Create', obj_t, [obj_t])
_bind('TToolButton_GetAllowAllUp', bool_t, [obj_t])
_bind('TToolButton_SetAllowAllUp', None, [obj_t, bool_t])
_bind('TToolButton_GetDown', bool_t, [obj_t])
_bind('TToolButton_SetDown', None, [obj_t, bool_t])
_bind('TToolButton_GetGrouped', bool_t, [obj_t])
_bind('TToolButton_SetGrouped', None, [obj_t, bool_t])
_bind('TToolButton_GetIndeterminate', bool_t, [obj_t])
_bind('TToolButton_SetIndeterminate', None, [obj_t, bool_t])
_bind('TToolButton_GetMarked', bool_t, [obj_t])
_bind('TToolButton_SetMarked', None, [obj_t, bool_t])
_bind('TToolButton_GetShowCaption', bool_t, [obj_t])
_bind('TToolButton_SetShowCaption', None, [obj_t, bool_t])
_bind('TToolButton_GetWrap', bool_t, [obj_t])
_bind('TToolButton_SetWrap', None, [obj_t, bool_t])
_bind('TToolButton_GetStyle', int_t, [obj_t])
_bind('TToolButton_SetStyle', None, [obj_t, int_t])
_bind('TToolButton_GetDropdownMenu', obj_t, [obj_t])
_bind('TToolButton_SetDropdownMenu', None, [obj_t, obj_t])
_bind('TToolButton_GetMenuItem', obj_t, [obj_t])
_bind('TToolButton_SetMenuItem', None, [obj_t, obj_t])
_bind('TToolButton_GetIndex', int_t, [obj_t])
_bind('TToolButton_Click', None, [obj_t])
_bind('TToolButton_ArrowClick', None, [obj_t])
_bind('TToolButton_PointInArrow', bool_t, [obj_t, int_t, int_t])
_bind('TToolButton_SetOnArrowClick', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCoolBar_Create', obj_t, [obj_t])
_bind('TCustomCoolBar_GetBands', obj_t, [obj_t])
_bind('TCustomCoolBar_AutosizeBands', None, [obj_t])
_bind('TCustomCoolBar_MouseToBandPos', None, [obj_t, int_t, int_t, POINTER(int_t), POINTER(bool_t)])
_bind('TCustomCoolBar_GetFixedSize', bool_t, [obj_t])
_bind('TCustomCoolBar_SetFixedSize', None, [obj_t, bool_t])
_bind('TCustomCoolBar_GetFixedOrder', bool_t, [obj_t])
_bind('TCustomCoolBar_SetFixedOrder', None, [obj_t, bool_t])
_bind('TCustomCoolBar_GetGrabStyle', int_t, [obj_t])
_bind('TCustomCoolBar_SetGrabStyle', None, [obj_t, int_t])
_bind('TCustomCoolBar_GetGrabWidth', int_t, [obj_t])
_bind('TCustomCoolBar_SetGrabWidth', None, [obj_t, int_t])
_bind('TCustomCoolBar_GetHorizontalSpacing', int_t, [obj_t])
_bind('TCustomCoolBar_SetHorizontalSpacing', None, [obj_t, int_t])
_bind('TCustomCoolBar_GetVerticalSpacing', int_t, [obj_t])
_bind('TCustomCoolBar_SetVerticalSpacing', None, [obj_t, int_t])
_bind('TCustomCoolBar_GetShowText', bool_t, [obj_t])
_bind('TCustomCoolBar_SetShowText', None, [obj_t, bool_t])
_bind('TCustomCoolBar_GetThemed', bool_t, [obj_t])
_bind('TCustomCoolBar_SetThemed', None, [obj_t, bool_t])
_bind('TCustomCoolBar_GetVertical', bool_t, [obj_t])
_bind('TCustomCoolBar_SetVertical', None, [obj_t, bool_t])
_bind('TCustomCoolBar_SetOnChange', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCoolBands_Add', obj_t, [obj_t])
_bind('TCoolBands_GetCount', int_t, [obj_t])
_bind('TCoolBands_GetItem', obj_t, [obj_t, int_t])
_bind('TCoolBands_Delete', None, [obj_t, int_t])
_bind('TCoolBands_Clear', None, [obj_t])
_bind('TCoolBands_BeginUpdate', None, [obj_t])
_bind('TCoolBands_EndUpdate', None, [obj_t])
_bind('TCoolBands_FindBand', obj_t, [obj_t, obj_t])
_bind('TCoolBands_FindBandIndex', int_t, [obj_t, obj_t])
_bind('TCoolBand_GetText', str_t, [obj_t])
_bind('TCoolBand_SetText', None, [obj_t, str_t])
_bind('TCoolBand_GetWidth', int_t, [obj_t])
_bind('TCoolBand_SetWidth', None, [obj_t, int_t])
_bind('TCoolBand_GetMinWidth', int_t, [obj_t])
_bind('TCoolBand_SetMinWidth', None, [obj_t, int_t])
_bind('TCoolBand_GetMinHeight', int_t, [obj_t])
_bind('TCoolBand_SetMinHeight', None, [obj_t, int_t])
_bind('TCoolBand_GetBreak', bool_t, [obj_t])
_bind('TCoolBand_SetBreak', None, [obj_t, bool_t])
_bind('TCoolBand_GetVisible', bool_t, [obj_t])
_bind('TCoolBand_SetVisible', None, [obj_t, bool_t])
_bind('TCoolBand_GetFixedSize', bool_t, [obj_t])
_bind('TCoolBand_SetFixedSize', None, [obj_t, bool_t])
_bind('TCoolBand_GetFixedBackground', bool_t, [obj_t])
_bind('TCoolBand_SetFixedBackground', None, [obj_t, bool_t])
_bind('TCoolBand_GetHorizontalOnly', bool_t, [obj_t])
_bind('TCoolBand_SetHorizontalOnly', None, [obj_t, bool_t])
_bind('TCoolBand_GetColor', int_t, [obj_t])
_bind('TCoolBand_SetColor', None, [obj_t, int_t])
_bind('TCoolBand_GetParentColor', bool_t, [obj_t])
_bind('TCoolBand_SetParentColor', None, [obj_t, bool_t])
_bind('TCoolBand_GetIndex', int_t, [obj_t])
_bind('TCoolBand_SetIndex', None, [obj_t, int_t])
_bind('TCoolBand_GetControl', obj_t, [obj_t])
_bind('TCoolBand_SetControl', None, [obj_t, obj_t])
_bind('TCoolBand_GetLeft', int_t, [obj_t])
_bind('TCoolBand_GetTop', int_t, [obj_t])
_bind('TCoolBand_GetRight', int_t, [obj_t])
_bind('TCoolBand_GetHeight', int_t, [obj_t])
_bind('TCoolBand_AutosizeWidth', None, [obj_t])
_bind('TStrings_GetCount', int_t, [obj_t])
_bind('TStrings_GetStrings', str_t, [obj_t, int_t])
_bind('TStrings_SetStrings', None, [obj_t, int_t, str_t])
_bind('TStrings_GetObjects', c_void_p, [obj_t, int_t])
_bind('TStrings_SetObjects', None, [obj_t, int_t, c_void_p])
_bind('TStrings_Add', int_t, [obj_t, str_t])
_bind('TStrings_AddObject', int_t, [obj_t, str_t, c_void_p])
_bind('TStrings_Insert', None, [obj_t, int_t, str_t])
_bind('TStrings_Delete', None, [obj_t, int_t])
_bind('TStrings_Clear', None, [obj_t])
_bind('TStrings_IndexOf', int_t, [obj_t, str_t])
_bind('TStrings_Exchange', None, [obj_t, int_t, int_t])
_bind('TStrings_Move', None, [obj_t, int_t, int_t])
_bind('TStrings_BeginUpdate', None, [obj_t])
_bind('TStrings_EndUpdate', None, [obj_t])
_bind('TStrings_GetText', str_t, [obj_t])
_bind('TStrings_SetText', None, [obj_t, str_t])
_bind('TStrings_GetCommaText', str_t, [obj_t])
_bind('TStrings_SetCommaText', None, [obj_t, str_t])
_bind('TStrings_Assign', None, [obj_t, obj_t])
_bind('TStrings_AddStrings', None, [obj_t, obj_t])
_bind('TStrings_GetNames', str_t, [obj_t, int_t])
_bind('TStrings_GetValues', str_t, [obj_t, str_t])
_bind('TStrings_SetValues', None, [obj_t, str_t, str_t])
_bind('TStrings_GetValueFromIndex', str_t, [obj_t, int_t])
_bind('TStrings_SetValueFromIndex', None, [obj_t, int_t, str_t])
_bind('TStrings_IndexOfName', int_t, [obj_t, str_t])
_bind('TStrings_GetDelimiter', c_char, [obj_t])
_bind('TStrings_SetDelimiter', None, [obj_t, c_char])
_bind('TStrings_GetStrictDelimiter', bool_t, [obj_t])
_bind('TStrings_SetStrictDelimiter', None, [obj_t, bool_t])
_bind('TStrings_GetDelimitedText', str_t, [obj_t])
_bind('TStrings_SetDelimitedText', None, [obj_t, str_t])
_bind('TStrings_LoadFromFile', None, [obj_t, str_t])
_bind('TStrings_SaveToFile', None, [obj_t, str_t])
_bind('TStringList_Create', obj_t, [])
_bind('TStringList_Destroy', None, [obj_t])
_bind('TStringList_Sort', None, [obj_t])
_bind('TStringList_Find', bool_t, [obj_t, str_t, POINTER(int_t)])
_bind('TStringList_GetSorted', bool_t, [obj_t])
_bind('TStringList_SetSorted', None, [obj_t, bool_t])
_bind('TStringList_GetDuplicates', int_t, [obj_t])
_bind('TStringList_SetDuplicates', None, [obj_t, int_t])
_bind('TStringList_GetCaseSensitive', bool_t, [obj_t])
_bind('TStringList_SetCaseSensitive', None, [obj_t, bool_t])
_bind('TGraphic_Destroy', None, [obj_t])
_bind('TGraphic_GetWidth', int_t, [obj_t])
_bind('TGraphic_SetWidth', None, [obj_t, int_t])
_bind('TGraphic_GetHeight', int_t, [obj_t])
_bind('TGraphic_SetHeight', None, [obj_t, int_t])
_bind('TGraphic_GetEmpty', bool_t, [obj_t])
_bind('TGraphic_GetTransparent', bool_t, [obj_t])
_bind('TGraphic_SetTransparent', None, [obj_t, bool_t])
_bind('TGraphic_LoadFromFile', None, [obj_t, str_t])
_bind('TGraphic_SaveToFile', None, [obj_t, str_t])
_bind('TGraphic_Assign', None, [obj_t, obj_t])
_bind('TGraphic_Clear', None, [obj_t])
_bind('TRasterImage_GetCanvas', obj_t, [obj_t])
_bind('TRasterImage_GetPixelFormat', int_t, [obj_t])
_bind('TRasterImage_SetPixelFormat', None, [obj_t, int_t])
_bind('TRasterImage_GetTransparentColor', int_t, [obj_t])
_bind('TRasterImage_SetTransparentColor', None, [obj_t, int_t])
_bind('TRasterImage_GetTransparentMode', int_t, [obj_t])
_bind('TRasterImage_SetTransparentMode', None, [obj_t, int_t])
_bind('TCustomBitmap_SetSize', None, [obj_t, int_t, int_t])
_bind('TBitmap_Create', obj_t, [])
_bind('TPortableNetworkGraphic_Create', obj_t, [])
_bind('TJPEGImage_Create', obj_t, [])
_bind('TJPEGImage_GetCompressionQuality', int_t, [obj_t])
_bind('TJPEGImage_SetCompressionQuality', None, [obj_t, int_t])
_bind('TPicture_Create', obj_t, [])
_bind('TPicture_Destroy', None, [obj_t])
_bind('TPicture_GetGraphic', obj_t, [obj_t])
_bind('TPicture_SetGraphic', None, [obj_t, obj_t])
_bind('TPicture_GetBitmap', obj_t, [obj_t])
_bind('TPicture_GetPNG', obj_t, [obj_t])
_bind('TPicture_GetJpeg', obj_t, [obj_t])
_bind('TPicture_GetWidth', int_t, [obj_t])
_bind('TPicture_GetHeight', int_t, [obj_t])
_bind('TPicture_LoadFromFile', None, [obj_t, str_t])
_bind('TPicture_SaveToFile', None, [obj_t, str_t])
_bind('TPicture_Assign', None, [obj_t, obj_t])
_bind('TPicture_Clear', None, [obj_t])
_bind('TImage_Create', obj_t, [obj_t])
_bind('TCustomImage_GetPicture', obj_t, [obj_t])
_bind('TCustomImage_SetPicture', None, [obj_t, obj_t])
_bind('TCustomImage_GetCanvas', obj_t, [obj_t])
_bind('TCustomImage_GetHasGraphic', bool_t, [obj_t])
_bind('TCustomImage_GetCenter', bool_t, [obj_t])
_bind('TCustomImage_SetCenter', None, [obj_t, bool_t])
_bind('TCustomImage_GetStretch', bool_t, [obj_t])
_bind('TCustomImage_SetStretch', None, [obj_t, bool_t])
_bind('TCustomImage_GetStretchOutEnabled', bool_t, [obj_t])
_bind('TCustomImage_SetStretchOutEnabled', None, [obj_t, bool_t])
_bind('TCustomImage_GetStretchInEnabled', bool_t, [obj_t])
_bind('TCustomImage_SetStretchInEnabled', None, [obj_t, bool_t])
_bind('TCustomImage_GetProportional', bool_t, [obj_t])
_bind('TCustomImage_SetProportional', None, [obj_t, bool_t])
_bind('TCustomImage_GetTransparent', bool_t, [obj_t])
_bind('TCustomImage_SetTransparent', None, [obj_t, bool_t])
_bind('TCustomImage_SetOnPictureChanged', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomBitBtn_GetGlyph', obj_t, [obj_t])
_bind('TCustomBitBtn_SetGlyph', None, [obj_t, obj_t])
_bind('TCustomBitBtn_GetNumGlyphs', int_t, [obj_t])
_bind('TCustomBitBtn_SetNumGlyphs', None, [obj_t, int_t])
_bind('TCustomBitBtn_GetLayout', int_t, [obj_t])
_bind('TCustomBitBtn_SetLayout', None, [obj_t, int_t])
_bind('TCustomBitBtn_GetMargin', int_t, [obj_t])
_bind('TCustomBitBtn_SetMargin', None, [obj_t, int_t])
_bind('TCustomBitBtn_GetSpacing', int_t, [obj_t])
_bind('TCustomBitBtn_SetSpacing', None, [obj_t, int_t])
_bind('TCustomSpeedButton_GetGlyph', obj_t, [obj_t])
_bind('TCustomSpeedButton_SetGlyph', None, [obj_t, obj_t])
_bind('TCustomSpeedButton_GetNumGlyphs', int_t, [obj_t])
_bind('TCustomSpeedButton_SetNumGlyphs', None, [obj_t, int_t])
_bind('TCustomSpeedButton_GetLayout', int_t, [obj_t])
_bind('TCustomSpeedButton_SetLayout', None, [obj_t, int_t])
_bind('TCustomSpeedButton_GetMargin', int_t, [obj_t])
_bind('TCustomSpeedButton_SetMargin', None, [obj_t, int_t])
_bind('TCustomSpeedButton_GetSpacing', int_t, [obj_t])
_bind('TCustomSpeedButton_SetSpacing', None, [obj_t, int_t])
_bind('TImageList_Create', obj_t, [obj_t])
_bind('TCustomImageList_GetWidth', int_t, [obj_t])
_bind('TCustomImageList_SetWidth', None, [obj_t, int_t])
_bind('TCustomImageList_GetHeight', int_t, [obj_t])
_bind('TCustomImageList_SetHeight', None, [obj_t, int_t])
_bind('TCustomImageList_GetCount', int_t, [obj_t])
_bind('TCustomImageList_GetMasked', bool_t, [obj_t])
_bind('TCustomImageList_SetMasked', None, [obj_t, bool_t])
_bind('TCustomImageList_GetBkColor', int_t, [obj_t])
_bind('TCustomImageList_SetBkColor', None, [obj_t, int_t])
_bind('TCustomImageList_GetDrawingStyle', int_t, [obj_t])
_bind('TCustomImageList_SetDrawingStyle', None, [obj_t, int_t])
_bind('TCustomImageList_Add', int_t, [obj_t, obj_t, obj_t])
_bind('TCustomImageList_AddSliced', int_t, [obj_t, obj_t, int_t, int_t])
_bind('TCustomImageList_AddMasked', int_t, [obj_t, obj_t, int_t])
_bind('TCustomImageList_Insert', None, [obj_t, int_t, obj_t, obj_t])
_bind('TCustomImageList_Replace', None, [obj_t, int_t, obj_t, obj_t])
_bind('TCustomImageList_Delete', None, [obj_t, int_t])
_bind('TCustomImageList_Clear', None, [obj_t])
_bind('TCustomImageList_Move', None, [obj_t, int_t, int_t])
_bind('TCustomImageList_GetBitmap', None, [obj_t, int_t, obj_t])
_bind('TCustomImageList_Draw', None, [obj_t, obj_t, int_t, int_t, int_t, bool_t])
_bind('TCustomImageList_BeginUpdate', None, [obj_t])
_bind('TCustomImageList_EndUpdate', None, [obj_t])
_bind('TCustomImageList_SetOnChange', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomImage_GetImages', obj_t, [obj_t])
_bind('TCustomImage_SetImages', None, [obj_t, obj_t])
_bind('TCustomImage_GetImageIndex', int_t, [obj_t])
_bind('TCustomImage_SetImageIndex', None, [obj_t, int_t])
_bind('TCustomBitBtn_GetImages', obj_t, [obj_t])
_bind('TCustomBitBtn_SetImages', None, [obj_t, obj_t])
_bind('TCustomBitBtn_GetImageIndex', int_t, [obj_t])
_bind('TCustomBitBtn_SetImageIndex', None, [obj_t, int_t])
_bind('TCustomSpeedButton_GetImages', obj_t, [obj_t])
_bind('TCustomSpeedButton_SetImages', None, [obj_t, obj_t])
_bind('TCustomSpeedButton_GetImageIndex', int_t, [obj_t])
_bind('TCustomSpeedButton_SetImageIndex', None, [obj_t, int_t])
_bind('TCustomTabControl_GetImages', obj_t, [obj_t])
_bind('TCustomTabControl_SetImages', None, [obj_t, obj_t])
_bind('TCustomPage_GetImageIndex', int_t, [obj_t])
_bind('TCustomPage_SetImageIndex', None, [obj_t, int_t])
_bind('TCustomTreeView_GetImages', obj_t, [obj_t])
_bind('TCustomTreeView_SetImages', None, [obj_t, obj_t])
_bind('TCustomTreeView_GetStateImages', obj_t, [obj_t])
_bind('TCustomTreeView_SetStateImages', None, [obj_t, obj_t])
_bind('TTreeNode_GetImageIndex', int_t, [obj_t])
_bind('TTreeNode_SetImageIndex', None, [obj_t, int_t])
_bind('TTreeNode_GetSelectedIndex', int_t, [obj_t])
_bind('TTreeNode_SetSelectedIndex', None, [obj_t, int_t])
_bind('TTreeNode_GetStateIndex', int_t, [obj_t])
_bind('TTreeNode_SetStateIndex', None, [obj_t, int_t])
_bind('TTreeNode_GetOverlayIndex', int_t, [obj_t])
_bind('TTreeNode_SetOverlayIndex', None, [obj_t, int_t])
_bind('TListView_GetLargeImages', obj_t, [obj_t])
_bind('TListView_SetLargeImages', None, [obj_t, obj_t])
_bind('TListView_GetSmallImages', obj_t, [obj_t])
_bind('TListView_SetSmallImages', None, [obj_t, obj_t])
_bind('TListView_GetStateImages', obj_t, [obj_t])
_bind('TListView_SetStateImages', None, [obj_t, obj_t])
_bind('TListItem_GetImageIndex', int_t, [obj_t])
_bind('TListItem_SetImageIndex', None, [obj_t, int_t])
_bind('TListItem_GetStateIndex', int_t, [obj_t])
_bind('TListItem_SetStateIndex', None, [obj_t, int_t])
_bind('TListColumn_GetImageIndex', int_t, [obj_t])
_bind('TListColumn_SetImageIndex', None, [obj_t, int_t])
_bind('TToolBar_GetImages', obj_t, [obj_t])
_bind('TToolBar_SetImages', None, [obj_t, obj_t])
_bind('TToolBar_GetHotImages', obj_t, [obj_t])
_bind('TToolBar_SetHotImages', None, [obj_t, obj_t])
_bind('TToolBar_GetDisabledImages', obj_t, [obj_t])
_bind('TToolBar_SetDisabledImages', None, [obj_t, obj_t])
_bind('TToolButton_GetImageIndex', int_t, [obj_t])
_bind('TToolButton_SetImageIndex', None, [obj_t, int_t])
_bind('TCustomHeaderControl_GetImages', obj_t, [obj_t])
_bind('TCustomHeaderControl_SetImages', None, [obj_t, obj_t])
_bind('THeaderSection_GetImageIndex', int_t, [obj_t])
_bind('THeaderSection_SetImageIndex', None, [obj_t, int_t])
_bind('TCustomCoolBar_GetImages', obj_t, [obj_t])
_bind('TCustomCoolBar_SetImages', None, [obj_t, obj_t])
_bind('TCustomCoolBar_GetBitmap', obj_t, [obj_t])
_bind('TCustomCoolBar_SetBitmap', None, [obj_t, obj_t])
_bind('TCoolBand_GetImageIndex', int_t, [obj_t])
_bind('TCoolBand_SetImageIndex', None, [obj_t, int_t])
_bind('TCoolBand_GetBitmap', obj_t, [obj_t])
_bind('TCoolBand_SetBitmap', None, [obj_t, obj_t])
_bind('TMenu_GetImages', obj_t, [obj_t])
_bind('TMenu_SetImages', None, [obj_t, obj_t])
_bind('TMenuItem_GetImageIndex', int_t, [obj_t])
_bind('TMenuItem_SetImageIndex', None, [obj_t, int_t])
_bind('TMenuItem_GetSubMenuImages', obj_t, [obj_t])
_bind('TMenuItem_SetSubMenuImages', None, [obj_t, obj_t])
_bind('TMenuItem_GetBitmap', obj_t, [obj_t])
_bind('TMenuItem_SetBitmap', None, [obj_t, obj_t])
_bind('TControl_GetColor', int_t, [obj_t])
_bind('TControl_SetColor', None, [obj_t, int_t])
_bind('TControl_GetFont', obj_t, [obj_t])
_bind('TControl_SetFont', None, [obj_t, obj_t])
_bind('TFont_GetStyle', uint_t, [obj_t])
_bind('TFont_SetStyle', None, [obj_t, uint_t])
_bind('TFont_Assign', None, [obj_t, obj_t])
_bind('TCommonDialog_Execute', bool_t, [obj_t])
_bind('TCommonDialog_GetTitle', str_t, [obj_t])
_bind('TCommonDialog_SetTitle', None, [obj_t, str_t])
_bind('TCommonDialog_SetOnShow', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCommonDialog_SetOnClose', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCommonDialog_SetOnCanClose', None, [obj_t, close_query_callback_t, c_void_p], 1)
_bind('TFileDialog_GetFileName', str_t, [obj_t])
_bind('TFileDialog_SetFileName', None, [obj_t, str_t])
_bind('TFileDialog_GetFilter', str_t, [obj_t])
_bind('TFileDialog_SetFilter', None, [obj_t, str_t])
_bind('TFileDialog_GetFilterIndex', int_t, [obj_t])
_bind('TFileDialog_SetFilterIndex', None, [obj_t, int_t])
_bind('TFileDialog_GetInitialDir', str_t, [obj_t])
_bind('TFileDialog_SetInitialDir', None, [obj_t, str_t])
_bind('TFileDialog_GetDefaultExt', str_t, [obj_t])
_bind('TFileDialog_SetDefaultExt', None, [obj_t, str_t])
_bind('TFileDialog_GetFiles', obj_t, [obj_t])
_bind('TOpenDialog_Create', obj_t, [obj_t])
_bind('TOpenDialog_GetOptions', uint_t, [obj_t])
_bind('TOpenDialog_SetOptions', None, [obj_t, uint_t])
_bind('TSaveDialog_Create', obj_t, [obj_t])
_bind('TSelectDirectoryDialog_Create', obj_t, [obj_t])
_bind('TColorDialog_Create', obj_t, [obj_t])
_bind('TColorDialog_GetColor', int_t, [obj_t])
_bind('TColorDialog_SetColor', None, [obj_t, int_t])
_bind('TColorDialog_GetCustomColors', obj_t, [obj_t])
_bind('TColorDialog_GetOptions', uint_t, [obj_t])
_bind('TColorDialog_SetOptions', None, [obj_t, uint_t])
_bind('TFontDialog_Create', obj_t, [obj_t])
_bind('TFontDialog_GetFont', obj_t, [obj_t])
_bind('TFontDialog_SetFont', None, [obj_t, obj_t])
_bind('TFontDialog_GetMinFontSize', int_t, [obj_t])
_bind('TFontDialog_SetMinFontSize', None, [obj_t, int_t])
_bind('TFontDialog_GetMaxFontSize', int_t, [obj_t])
_bind('TFontDialog_SetMaxFontSize', None, [obj_t, int_t])
_bind('TFontDialog_GetOptions', uint_t, [obj_t])
_bind('TFontDialog_SetOptions', None, [obj_t, uint_t])
_bind('TFindDialog_Create', obj_t, [obj_t])
_bind('TReplaceDialog_Create', obj_t, [obj_t])
_bind('TFindDialog_GetFindText', str_t, [obj_t])
_bind('TFindDialog_SetFindText', None, [obj_t, str_t])
_bind('TFindDialog_GetReplaceText', str_t, [obj_t])
_bind('TFindDialog_SetReplaceText', None, [obj_t, str_t])
_bind('TFindDialog_GetOptions', uint_t, [obj_t])
_bind('TFindDialog_SetOptions', None, [obj_t, uint_t])
_bind('TFindDialog_GetLeft', int_t, [obj_t])
_bind('TFindDialog_SetLeft', None, [obj_t, int_t])
_bind('TFindDialog_GetTop', int_t, [obj_t])
_bind('TFindDialog_SetTop', None, [obj_t, int_t])
_bind('TFindDialog_CloseDialog', None, [obj_t])
_bind('TFindDialog_SetOnFind', None, [obj_t, callback_t, c_void_p], 1)
_bind('TFindDialog_SetOnReplace', None, [obj_t, callback_t, c_void_p], 1)
_bind('TComponent_GetTag', iptr_t, [obj_t])
_bind('TComponent_SetTag', None, [obj_t, iptr_t])
_bind('TControl_GetAnchors', uint_t, [obj_t])
_bind('TControl_SetAnchors', None, [obj_t, uint_t])
_bind('TControl_GetBorderSpacing', obj_t, [obj_t])
_bind('TControl_SetBorderSpacing', None, [obj_t, obj_t])
_bind('TControl_GetConstraints', obj_t, [obj_t])
_bind('TControl_SetConstraints', None, [obj_t, obj_t])
_bind('TControl_GetHint', str_t, [obj_t])
_bind('TControl_SetHint', None, [obj_t, str_t])
_bind('TControl_GetShowHint', bool_t, [obj_t])
_bind('TControl_SetShowHint', None, [obj_t, bool_t])
_bind('TControl_GetCursor', int_t, [obj_t])
_bind('TControl_SetCursor', None, [obj_t, int_t])
_bind('TControl_GetParentColor', bool_t, [obj_t])
_bind('TControl_SetParentColor', None, [obj_t, bool_t])
_bind('TControl_GetParentFont', bool_t, [obj_t])
_bind('TControl_SetParentFont', None, [obj_t, bool_t])
_bind('TControl_GetParentShowHint', bool_t, [obj_t])
_bind('TControl_SetParentShowHint', None, [obj_t, bool_t])
_bind('TWinControl_GetTabOrder', int_t, [obj_t])
_bind('TWinControl_SetTabOrder', None, [obj_t, int_t])
_bind('TWinControl_GetTabStop', bool_t, [obj_t])
_bind('TWinControl_SetTabStop', None, [obj_t, bool_t])
_bind('TSizeConstraints_GetMinWidth', int_t, [obj_t])
_bind('TSizeConstraints_SetMinWidth', None, [obj_t, int_t])
_bind('TSizeConstraints_GetMinHeight', int_t, [obj_t])
_bind('TSizeConstraints_SetMinHeight', None, [obj_t, int_t])
_bind('TSizeConstraints_GetMaxWidth', int_t, [obj_t])
_bind('TSizeConstraints_SetMaxWidth', None, [obj_t, int_t])
_bind('TSizeConstraints_GetMaxHeight', int_t, [obj_t])
_bind('TSizeConstraints_SetMaxHeight', None, [obj_t, int_t])
_bind('TControlBorderSpacing_GetLeft', int_t, [obj_t])
_bind('TControlBorderSpacing_SetLeft', None, [obj_t, int_t])
_bind('TControlBorderSpacing_GetTop', int_t, [obj_t])
_bind('TControlBorderSpacing_SetTop', None, [obj_t, int_t])
_bind('TControlBorderSpacing_GetRight', int_t, [obj_t])
_bind('TControlBorderSpacing_SetRight', None, [obj_t, int_t])
_bind('TControlBorderSpacing_GetBottom', int_t, [obj_t])
_bind('TControlBorderSpacing_SetBottom', None, [obj_t, int_t])
_bind('TControlBorderSpacing_GetAround', int_t, [obj_t])
_bind('TControlBorderSpacing_SetAround', None, [obj_t, int_t])
_bind('TControlBorderSpacing_GetInnerBorder', int_t, [obj_t])
_bind('TControlBorderSpacing_SetInnerBorder', None, [obj_t, int_t])
_bind('TCustomForm_GetModalResult', int_t, [obj_t])
_bind('TCustomForm_SetModalResult', None, [obj_t, int_t])
_bind('TCustomForm_GetBorderStyle', int_t, [obj_t])
_bind('TCustomForm_SetBorderStyle', None, [obj_t, int_t])
_bind('TCustomForm_GetPosition', int_t, [obj_t])
_bind('TCustomForm_SetPosition', None, [obj_t, int_t])
_bind('TCustomForm_GetWindowState', int_t, [obj_t])
_bind('TCustomForm_SetWindowState', None, [obj_t, int_t])
_bind('TCustomForm_GetBorderIcons', uint_t, [obj_t])
_bind('TCustomForm_SetBorderIcons', None, [obj_t, uint_t])
_bind('TCustomForm_GetFormStyle', int_t, [obj_t])
_bind('TCustomForm_SetFormStyle', None, [obj_t, int_t])
_bind('TCustomForm_GetKeyPreview', bool_t, [obj_t])
_bind('TCustomForm_SetKeyPreview', None, [obj_t, bool_t])
_bind('TCustomForm_GetActiveControl', obj_t, [obj_t])
_bind('TCustomForm_SetActiveControl', None, [obj_t, obj_t])
_bind('TCustomButton_GetModalResult', int_t, [obj_t])
_bind('TCustomButton_SetModalResult', None, [obj_t, int_t])
_bind('TCustomButton_GetDefault', bool_t, [obj_t])
_bind('TCustomButton_SetDefault', None, [obj_t, bool_t])
_bind('TCustomButton_GetCancel', bool_t, [obj_t])
_bind('TCustomButton_SetCancel', None, [obj_t, bool_t])
_bind('Dialogs_ShowMessage', None, [str_t])
_bind('Dialogs_MessageDlg', int_t, [str_t, str_t, int_t, uint_t, int_t])
_bind('Dialogs_InputBox', str_t, [str_t, str_t, str_t])
_bind('Dialogs_PasswordBox', str_t, [str_t, str_t])
_bind('Dialogs_InputQuery', str_t, [str_t, str_t, str_t, POINTER(bool_t)])
_bind('TApplication_MessageBox', int_t, [obj_t, str_t, str_t, int_t])
_bind('TControl_GetClientWidth', int_t, [obj_t])
_bind('TControl_SetClientWidth', None, [obj_t, int_t])
_bind('TControl_GetClientHeight', int_t, [obj_t])
_bind('TControl_SetClientHeight', None, [obj_t, int_t])
_bind('TControl_Invalidate', None, [obj_t])
_bind('TControl_Repaint', None, [obj_t])
_bind('TControl_Refresh', None, [obj_t])
_bind('TControl_Update', None, [obj_t])
_bind('TControl_BringToFront', None, [obj_t])
_bind('TControl_SendToBack', None, [obj_t])
_bind('TControl_SetBounds', None, [obj_t, int_t, int_t, int_t, int_t])
_bind('TWinControl_SetFocus', None, [obj_t])
_bind('TWinControl_CanFocus', bool_t, [obj_t])
_bind('TWinControl_Focused', bool_t, [obj_t])
_bind('TCustomEdit_GetSelStart', int_t, [obj_t])
_bind('TCustomEdit_SetSelStart', None, [obj_t, int_t])
_bind('TCustomEdit_GetSelLength', int_t, [obj_t])
_bind('TCustomEdit_SetSelLength', None, [obj_t, int_t])
_bind('TCustomEdit_GetSelText', str_t, [obj_t])
_bind('TCustomEdit_SetSelText', None, [obj_t, str_t])
_bind('TCustomEdit_GetModified', bool_t, [obj_t])
_bind('TCustomEdit_SetModified', None, [obj_t, bool_t])
_bind('TCustomEdit_GetCanUndo', bool_t, [obj_t])
_bind('TCustomEdit_GetPasswordChar', c_char, [obj_t])
_bind('TCustomEdit_SetPasswordChar', None, [obj_t, c_char])
_bind('TCustomEdit_GetEchoMode', int_t, [obj_t])
_bind('TCustomEdit_SetEchoMode', None, [obj_t, int_t])
_bind('TCustomEdit_GetCharCase', int_t, [obj_t])
_bind('TCustomEdit_SetCharCase', None, [obj_t, int_t])
_bind('TCustomEdit_GetAlignment', int_t, [obj_t])
_bind('TCustomEdit_SetAlignment', None, [obj_t, int_t])
_bind('TCustomEdit_GetTextHint', str_t, [obj_t])
_bind('TCustomEdit_SetTextHint', None, [obj_t, str_t])
_bind('TCustomEdit_GetNumbersOnly', bool_t, [obj_t])
_bind('TCustomEdit_SetNumbersOnly', None, [obj_t, bool_t])
_bind('TCustomEdit_GetAutoSelect', bool_t, [obj_t])
_bind('TCustomEdit_SetAutoSelect', None, [obj_t, bool_t])
_bind('TCustomEdit_GetHideSelection', bool_t, [obj_t])
_bind('TCustomEdit_SetHideSelection', None, [obj_t, bool_t])
_bind('TCustomEdit_GetCaretPos', None, [obj_t, POINTER(int_t), POINTER(int_t)])
_bind('TCustomEdit_SetCaretPos', None, [obj_t, int_t, int_t])
_bind('TCustomEdit_SelectAll', None, [obj_t])
_bind('TCustomEdit_ClearSelection', None, [obj_t])
_bind('TCustomEdit_Clear', None, [obj_t])
_bind('TCustomEdit_CopyToClipboard', None, [obj_t])
_bind('TCustomEdit_CutToClipboard', None, [obj_t])
_bind('TCustomEdit_PasteFromClipboard', None, [obj_t])
_bind('TCustomEdit_Undo', None, [obj_t])
_bind('TCustomMemo_GetWordWrap', bool_t, [obj_t])
_bind('TCustomMemo_SetWordWrap', None, [obj_t, bool_t])
_bind('TCustomMemo_GetWantReturns', bool_t, [obj_t])
_bind('TCustomMemo_SetWantReturns', None, [obj_t, bool_t])
_bind('TCustomMemo_GetWantTabs', bool_t, [obj_t])
_bind('TCustomMemo_SetWantTabs', None, [obj_t, bool_t])
_bind('TCustomMemo_Append', None, [obj_t, str_t])
_bind('TCustomLabel_GetAlignment', int_t, [obj_t])
_bind('TCustomLabel_SetAlignment', None, [obj_t, int_t])
_bind('TCustomLabel_GetLayout', int_t, [obj_t])
_bind('TCustomLabel_SetLayout', None, [obj_t, int_t])
_bind('TCustomLabel_GetWordWrap', bool_t, [obj_t])
_bind('TCustomLabel_SetWordWrap', None, [obj_t, bool_t])
_bind('TCustomLabel_GetTransparent', bool_t, [obj_t])
_bind('TCustomLabel_SetTransparent', None, [obj_t, bool_t])
_bind('TCustomLabel_GetFocusControl', obj_t, [obj_t])
_bind('TCustomLabel_SetFocusControl', None, [obj_t, obj_t])
_bind('TCustomLabel_GetShowAccelChar', bool_t, [obj_t])
_bind('TCustomLabel_SetShowAccelChar', None, [obj_t, bool_t])
_bind('TWinControl_SetOnEnter', None, [obj_t, callback_t, c_void_p], 1)
_bind('TWinControl_SetOnExit', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomListBox_GetMultiSelect', bool_t, [obj_t])
_bind('TCustomListBox_SetMultiSelect', None, [obj_t, bool_t])
_bind('TCustomListBox_GetExtendedSelect', bool_t, [obj_t])
_bind('TCustomListBox_SetExtendedSelect', None, [obj_t, bool_t])
_bind('TCustomListBox_GetSorted', bool_t, [obj_t])
_bind('TCustomListBox_SetSorted', None, [obj_t, bool_t])
_bind('TCustomListBox_GetTopIndex', int_t, [obj_t])
_bind('TCustomListBox_SetTopIndex', None, [obj_t, int_t])
_bind('TCustomListBox_GetSelCount', int_t, [obj_t])
_bind('TCustomListBox_GetSelected', bool_t, [obj_t, int_t])
_bind('TCustomListBox_SetSelected', None, [obj_t, int_t, bool_t])
_bind('TCustomListBox_ClearSelection', None, [obj_t])
_bind('TCustomListBox_SelectAll', None, [obj_t])
_bind('TCustomListBox_ItemAtPos', int_t, [obj_t, int_t, int_t, bool_t])
_bind('TCustomListBox_SetOnSelectionChange', None, [obj_t, bool_callback_t, c_void_p], 1)
_bind('TCustomComboBox_GetStyle', int_t, [obj_t])
_bind('TCustomComboBox_SetStyle', None, [obj_t, int_t])
_bind('TCustomComboBox_GetDropDownCount', int_t, [obj_t])
_bind('TCustomComboBox_SetDropDownCount', None, [obj_t, int_t])
_bind('TCustomComboBox_GetSorted', bool_t, [obj_t])
_bind('TCustomComboBox_SetSorted', None, [obj_t, bool_t])
_bind('TCustomComboBox_GetReadOnly', bool_t, [obj_t])
_bind('TCustomComboBox_SetReadOnly', None, [obj_t, bool_t])
_bind('TCustomComboBox_GetDroppedDown', bool_t, [obj_t])
_bind('TCustomComboBox_SetDroppedDown', None, [obj_t, bool_t])
_bind('TCustomComboBox_GetAutoComplete', bool_t, [obj_t])
_bind('TCustomComboBox_SetAutoComplete', None, [obj_t, bool_t])
_bind('TCustomComboBox_SetOnSelect', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomComboBox_SetOnDropDown', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomComboBox_SetOnCloseUp', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCustomCheckBox_GetState', int_t, [obj_t])
_bind('TCustomCheckBox_SetState', None, [obj_t, int_t])
_bind('TCustomCheckBox_GetAllowGrayed', bool_t, [obj_t])
_bind('TCustomCheckBox_SetAllowGrayed', None, [obj_t, bool_t])
_bind('TCustomCheckBox_SetOnChange', None, [obj_t, callback_t, c_void_p], 1)
_bind('TApplication_GetExeName', str_t, [obj_t])
_bind('TApplication_GetHint', str_t, [obj_t])
_bind('TApplication_SetHint', None, [obj_t, str_t])
_bind('TApplication_GetShowHint', bool_t, [obj_t])
_bind('TApplication_SetShowHint', None, [obj_t, bool_t])
_bind('TApplication_GetHintPause', int_t, [obj_t])
_bind('TApplication_SetHintPause', None, [obj_t, int_t])
_bind('TApplication_GetHintHidePause', int_t, [obj_t])
_bind('TApplication_SetHintHidePause', None, [obj_t, int_t])
_bind('TApplication_Minimize', None, [obj_t])
_bind('TApplication_Restore', None, [obj_t])
_bind('TApplication_BringToFront', None, [obj_t])
_bind('TApplication_SetOnIdle', None, [obj_t, close_query_callback_t, c_void_p], 1)
_bind('TApplication_SetOnException', None, [obj_t, exception_callback_t, c_void_p], 1)
_bind('TStatusBar_GetPanels', obj_t, [obj_t])
_bind('TStatusBar_GetSizeGrip', bool_t, [obj_t])
_bind('TStatusBar_SetSizeGrip', None, [obj_t, bool_t])
_bind('TStatusBar_GetAutoHint', bool_t, [obj_t])
_bind('TStatusBar_SetAutoHint', None, [obj_t, bool_t])
_bind('TStatusBar_GetCanvas', obj_t, [obj_t])
_bind('TStatusBar_GetPanelIndexAt', int_t, [obj_t, int_t, int_t])
_bind('TStatusBar_BeginUpdate', None, [obj_t])
_bind('TStatusBar_EndUpdate', None, [obj_t])
_bind('TStatusBar_SetOnDrawPanel', None, [obj_t, item_rect_callback_t, c_void_p], 1)
_bind('TStatusBar_SetOnHint', None, [obj_t, callback_t, c_void_p], 1)
_bind('TStatusPanels_Add', obj_t, [obj_t])
_bind('TStatusPanels_Insert', obj_t, [obj_t, int_t])
_bind('TStatusPanels_Delete', None, [obj_t, int_t])
_bind('TStatusPanels_Clear', None, [obj_t])
_bind('TStatusPanels_GetCount', int_t, [obj_t])
_bind('TStatusPanels_GetItem', obj_t, [obj_t, int_t])
_bind('TStatusPanels_BeginUpdate', None, [obj_t])
_bind('TStatusPanels_EndUpdate', None, [obj_t])
_bind('TStatusPanel_GetText', str_t, [obj_t])
_bind('TStatusPanel_SetText', None, [obj_t, str_t])
_bind('TStatusPanel_GetWidth', int_t, [obj_t])
_bind('TStatusPanel_SetWidth', None, [obj_t, int_t])
_bind('TStatusPanel_GetAlignment', int_t, [obj_t])
_bind('TStatusPanel_SetAlignment', None, [obj_t, int_t])
_bind('TStatusPanel_GetBevel', int_t, [obj_t])
_bind('TStatusPanel_SetBevel', None, [obj_t, int_t])
_bind('TStatusPanel_GetStyle', int_t, [obj_t])
_bind('TStatusPanel_SetStyle', None, [obj_t, int_t])
_bind('TStatusPanel_GetIndex', int_t, [obj_t])
_bind('TStatusPanel_SetIndex', None, [obj_t, int_t])
_bind('TCustomControl_GetCanvas', obj_t, [obj_t])
_bind('TCustomControl_SetOnPaint', None, [obj_t, callback_t, c_void_p], 1)
_bind('TCanvas_TextWidth', int_t, [obj_t, str_t])
_bind('TCanvas_TextHeight', int_t, [obj_t, str_t])
_bind('TCanvas_TextRect', None, [obj_t, int_t, int_t, int_t, int_t, int_t, int_t, str_t])
_bind('TCanvas_Polygon', None, [obj_t, POINTER(int_t), int_t])
_bind('TCanvas_Polyline', None, [obj_t, POINTER(int_t), int_t])
_bind('TCanvas_RoundRect', None, [obj_t, int_t, int_t, int_t, int_t, int_t, int_t])
_bind('TCanvas_Arc', None, [obj_t, int_t, int_t, int_t, int_t, int_t, int_t, int_t, int_t])
_bind('TCanvas_Pie', None, [obj_t, int_t, int_t, int_t, int_t, int_t, int_t, int_t, int_t])
_bind('TCanvas_Chord', None, [obj_t, int_t, int_t, int_t, int_t, int_t, int_t, int_t, int_t])
_bind('TCanvas_FrameRect', None, [obj_t, int_t, int_t, int_t, int_t])
_bind('TCanvas_CopyRect', None, [obj_t, int_t, int_t, int_t, int_t, obj_t, int_t, int_t, int_t, int_t])
_bind('TPen_GetStyle', int_t, [obj_t])
_bind('TPen_SetStyle', None, [obj_t, int_t])
_bind('TPen_GetMode', int_t, [obj_t])
_bind('TPen_SetMode', None, [obj_t, int_t])
_bind('TBrush_GetStyle', int_t, [obj_t])
_bind('TBrush_SetStyle', None, [obj_t, int_t])
_bind('TFont_GetHeight', int_t, [obj_t])
_bind('TFont_SetHeight', None, [obj_t, int_t])
_bind('TFont_GetOrientation', int_t, [obj_t])
_bind('TFont_SetOrientation', None, [obj_t, int_t])
_bind('TFont_GetQuality', int_t, [obj_t])
_bind('TFont_SetQuality', None, [obj_t, int_t])
_bind('TBasicAction_Execute', bool_t, [obj_t])
_bind('TBasicAction_Update', bool_t, [obj_t])
_bind('TBasicAction_GetActionComponent', obj_t, [obj_t])
_bind('TBasicAction_SetOnExecute', None, [obj_t, callback_t, c_void_p], 1)
_bind('TBasicAction_SetOnUpdate', None, [obj_t, callback_t, c_void_p], 1)
_bind('TContainedAction_GetActionList', obj_t, [obj_t])
_bind('TContainedAction_SetActionList', None, [obj_t, obj_t])
_bind('TContainedAction_GetCategory', str_t, [obj_t])
_bind('TContainedAction_SetCategory', None, [obj_t, str_t])
_bind('TContainedAction_GetIndex', int_t, [obj_t])
_bind('TContainedAction_SetIndex', None, [obj_t, int_t])
_bind('TCustomAction_GetCaption', str_t, [obj_t])
_bind('TCustomAction_SetCaption', None, [obj_t, str_t])
_bind('TCustomAction_GetHint', str_t, [obj_t])
_bind('TCustomAction_SetHint', None, [obj_t, str_t])
_bind('TCustomAction_GetChecked', bool_t, [obj_t])
_bind('TCustomAction_SetChecked', None, [obj_t, bool_t])
_bind('TCustomAction_GetAutoCheck', bool_t, [obj_t])
_bind('TCustomAction_SetAutoCheck', None, [obj_t, bool_t])
_bind('TCustomAction_GetEnabled', bool_t, [obj_t])
_bind('TCustomAction_SetEnabled', None, [obj_t, bool_t])
_bind('TCustomAction_GetVisible', bool_t, [obj_t])
_bind('TCustomAction_SetVisible', None, [obj_t, bool_t])
_bind('TCustomAction_GetDisableIfNoHandler', bool_t, [obj_t])
_bind('TCustomAction_SetDisableIfNoHandler', None, [obj_t, bool_t])
_bind('TCustomAction_GetGroupIndex', int_t, [obj_t])
_bind('TCustomAction_SetGroupIndex', None, [obj_t, int_t])
_bind('TCustomAction_GetImageIndex', int_t, [obj_t])
_bind('TCustomAction_SetImageIndex', None, [obj_t, int_t])
_bind('TCustomAction_GetShortCut', int_t, [obj_t])
_bind('TCustomAction_SetShortCut', None, [obj_t, int_t])
_bind('TAction_Create', obj_t, [obj_t])
_bind('TCustomActionList_GetActionCount', int_t, [obj_t])
_bind('TCustomActionList_GetActions', obj_t, [obj_t, int_t])
_bind('TCustomActionList_GetImages', obj_t, [obj_t])
_bind('TCustomActionList_SetImages', None, [obj_t, obj_t])
_bind('TCustomActionList_GetState', int_t, [obj_t])
_bind('TCustomActionList_SetState', None, [obj_t, int_t])
_bind('TCustomActionList_SetOnExecute', None, [obj_t, item_allow_callback_t, c_void_p], 1)
_bind('TCustomActionList_SetOnUpdate', None, [obj_t, item_allow_callback_t, c_void_p], 1)
_bind('TActionList_Create', obj_t, [obj_t])
_bind('TControl_GetAction', obj_t, [obj_t])
_bind('TControl_SetAction', None, [obj_t, obj_t])
_bind('TMenuItem_GetAction', obj_t, [obj_t])
_bind('TMenuItem_SetAction', None, [obj_t, obj_t])
